# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class RoomData:
    room_label: str
    """The full room label in the spreadsheet (e.g. South Plaza (X-2, Y-3) - ren223 (Main))."""
    room_area: str
    """The map area in-game (e.g. South Plaza)."""
    region_name: str
    """The Archipelago region name."""
    global_room_id: str
    """The global room ID (e.g. city/ren223 (Main))."""
    suffix: str
    """The Archipelago region suffix (e.g. (Main))."""
    full_global_room_id: str = field(init=False, repr=False)
    """The full global room ID (including suffix)."""

    def __post_init__(self) -> None:
        self.full_global_room_id = f"{self.global_room_id}{self.suffix}"


@dataclass
class ConnectionData:
    start_region_name: str
    """The connection start's Archipelago region name."""
    end_region_name: str
    """The connection end's Archipelago region name."""


ROOMS: list[RoomData] = [
    RoomData(room_label="Menu", room_area="Menu", region_name="Menu", global_room_id="", suffix=""),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (North)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (North)",
        global_room_id="city/ren355",
        suffix=" (North)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (South)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (South)",
        global_room_id="city/ren355",
        suffix=" (South)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (West)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (West)",
        global_room_id="city/ren355",
        suffix=" (West)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (East)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (East)",
        global_room_id="city/ren355",
        suffix=" (East)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-4) - ren4064",
        room_area="South Plaza",
        region_name="SP (-2,-4)",
        global_room_id="city/ren4064",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y-4) - ren4066",
        room_area="South Plaza",
        region_name="SP (+1,-4)",
        global_room_id="city/ren4066",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Main)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Main)",
        global_room_id="city/ren223",
        suffix=" (Main)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (South)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (South)",
        global_room_id="city/ren223",
        suffix=" (South)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southwest)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Southwest)",
        global_room_id="city/ren223",
        suffix=" (Southwest)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southeast)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Southeast)",
        global_room_id="city/ren223",
        suffix=" (Southeast)",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+3) - ren4152",
        room_area="South Plaza",
        region_name="SP (-3,+3)",
        global_room_id="city/ren4152",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+4) - yug4930",
        room_area="South Plaza",
        region_name="SP (-3,+4)",
        global_room_id="city/yug4930",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y+4) - yug5210",
        room_area="South Plaza",
        region_name="SP (-2,+4)",
        global_room_id="city/yug5210",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (North)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (North)",
        global_room_id="city/lor2248",
        suffix=" (North)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (South)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (South)",
        global_room_id="city/lor2248",
        suffix=" (South)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (Southeast)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (Southeast)",
        global_room_id="city/lor2248",
        suffix=" (Southeast)",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (West)",
        room_area="South Plaza",
        region_name="SP (+1,+4) (West)",
        global_room_id="city/yug4939",
        suffix=" (West)",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (East)",
        room_area="South Plaza",
        region_name="SP (+1,+4) (East)",
        global_room_id="city/yug4939",
        suffix=" (East)",
    ),
    RoomData(
        room_label="South Plaza (X+2, Y+4) - yug5154",
        room_area="South Plaza",
        region_name="SP (+2,+4)",
        global_room_id="city/yug5154",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (Interiors) (X-1, Y+1) - ren85",
        room_area="South Plaza (Interiors)",
        region_name="SP Interiors (-1,+1)",
        global_room_id="city_interiors/ren85",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-6) - lor230",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,-6)",
        global_room_id="city_underground/lor230",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-5) - ren984",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,-5)",
        global_room_id="city_underground/ren984",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+4) - lor871",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+4)",
        global_room_id="city_underground/lor871",
        suffix="",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (West)",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+5) (West)",
        global_room_id="city_underground/yug1700",
        suffix=" (West)",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (East)",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+5) (East)",
        global_room_id="city_underground/yug1700",
        suffix=" (East)",
    ),
]

CONNECTIONS: list[ConnectionData] = [
    ConnectionData(start_region_name="Menu", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-1,-6) (North)", end_region_name="SP (-1,-6) (South)"),
    ConnectionData(start_region_name="SP (-1,-6) (North)", end_region_name="SP Sewers (-1,-6)"),
    ConnectionData(start_region_name="SP Sewers (-1,-6)", end_region_name="SP (-1,-6) (North)"),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP Sewers (-1,-5)"),
    ConnectionData(start_region_name="SP Sewers (-1,-5)", end_region_name="SP (-1,-6) (South)"),
    ConnectionData(start_region_name="SP (-2,-4)", end_region_name="SP (-1,-6) (South)"),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP (-2,-4)"),
    ConnectionData(start_region_name="SP (+1,-4)", end_region_name="SP (-1,-6) (South)"),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP (+1,-4)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (-2,-4)"),
    ConnectionData(start_region_name="SP (-2,-4)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (+1,-4)"),
    ConnectionData(start_region_name="SP (+1,-4)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (-2,-3) (South)"),
    ConnectionData(start_region_name="SP (-2,-3) (South)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (-2,-3) (Southwest)"),
    ConnectionData(start_region_name="SP (-2,-3) (Southwest)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (-2,-3) (Southeast)"),
    ConnectionData(start_region_name="SP (-2,-3) (Southeast)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP Interiors (-1,+1)"),
    ConnectionData(start_region_name="SP Interiors (-1,+1)", end_region_name="SP (-2,-3) (Main)"),
    ConnectionData(start_region_name="SP (-2,-3) (South)", end_region_name="SP (-1,+4) (North)"),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (-2,-3) (South)"),
    ConnectionData(start_region_name="SP (-2,-3) (Southwest)", end_region_name="SP (-3,+3)"),
    ConnectionData(start_region_name="SP (-3,+3)", end_region_name="SP (-2,-3) (Southwest)"),
    ConnectionData(start_region_name="SP (-2,+4)", end_region_name="SP (-3,+4)"),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (-2,+4)"),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (+1,+4) (West)"),
    ConnectionData(start_region_name="SP (-1,+4) (South)", end_region_name="SP (-1,+4) (North)"),
    ConnectionData(start_region_name="SP (-1,+4) (South)", end_region_name="SP Sewers (-1,+4)"),
    ConnectionData(start_region_name="SP Sewers (-1,+4)", end_region_name="SP (-1,+4) (South)"),
    ConnectionData(start_region_name="SP (-1,+4) (Southeast)", end_region_name="SP (-1,+4) (South)"),
    ConnectionData(start_region_name="SP (+1,+4) (West)", end_region_name="SP (+1,+4) (East)"),
    ConnectionData(start_region_name="SP (+1,+4) (East)", end_region_name="SP (+2,+4)"),
    ConnectionData(start_region_name="SP Sewers (-1,-5)", end_region_name="SP Sewers (-1,-6)"),
    ConnectionData(start_region_name="SP Sewers (-1,+4)", end_region_name="SP Sewers (-1,+5) (West)"),
    ConnectionData(start_region_name="SP Sewers (-1,+5) (West)", end_region_name="SP Sewers (-1,+5) (East)"),
]
