# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from dataclasses import dataclass, field

from BaseClasses import Location


class PipLocation(Location):
    game = "Pipistrello and the Cursed Yoyo"


@dataclass
class LocationData:
    region_name: str
    """The Archipelago region name."""
    location_name: str
    """The Archipelago location name (excluding region name)."""
    global_object_id: str
    """The global object ID in-game (e.g. city/ren223/yug2063)."""
    map_name: str
    """The Canva map name (e.g. Moneybag 1)."""
    id: int
    """The Archipelago location ID (e.g. 1)."""
    full_location_name: str = field(init=False, repr=False)
    """The full Archipelago location name (including region name)."""

    def __post_init__(self) -> None:
        self.full_location_name = f"{self.region_name}: {self.location_name}"


@dataclass
class EventData:
    region_name: str
    """The Archipelago region name."""
    location_name: str
    """The Archipelago location name (excluding region name)."""
    item_name: str
    """The Archipelago event item name (excluding region/location name)."""
    global_object_id: str
    """The global object ID in-game (e.g. city/ren223/yug5535)."""
    map_name: str
    """The Canva map name (e.g. Moneybag 1)."""
    full_location_name: str = field(init=False, repr=False)
    """The full Archipelago location name (including region name)."""
    full_item_name: str = field(init=False, repr=False)
    """The full Archipelago item name (including region/location name)."""

    def __post_init__(self) -> None:
        self.full_location_name = f"{self.region_name}: {self.location_name}"
        # self.full_item_name = f"{self.full_location_name}: {self.item_name}"
        self.full_item_name = f"{self.full_location_name}"


LOCATION_DATA: list[LocationData] = [
    LocationData(
        region_name="SP (-2,+4)",
        location_name="Pitcher's Badge",
        global_object_id="city/yug5210/yug5250",
        map_name="Badge (Pitcher's)",
        id=141,
    ),
    LocationData(
        region_name="SP (+2,+4)",
        location_name="BP Shard",
        global_object_id="city/yug5154/yug5202",
        map_name="BP Shard 1",
        id=151,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Combat (top-right, optional) - Reward",
        global_object_id="city/ren223/ren4805",
        map_name="Combat 1 (optional)",
        id=171,
    ),
    LocationData(
        region_name="SP (-3,+3)",
        location_name="Combat - Reward",
        global_object_id="city/ren4152/lor2096",
        map_name="Combat 2",
        id=191,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Money Bag (bottom-left, behind building)",
        global_object_id="city/ren223/cap369",
        map_name="Moneybag 1",
        id=271,
    ),
    LocationData(
        region_name="SP (-2,-3) (Southwest)",
        location_name="Money Bag",
        global_object_id="city/ren223/lor3388",
        map_name="Moneybag 2",
        id=281,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Money Bag (top-center)",
        global_object_id="city/ren223/lor380",
        map_name="Moneybag 3",
        id=291,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Money Bag (behind statue)",
        global_object_id="city/ren223/lor397",
        map_name="Moneybag 4",
        id=301,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Money Bag (bottom-right)",
        global_object_id="city/ren223/ren4803",
        map_name="Moneybag 5",
        id=311,
    ),
    LocationData(
        region_name="SP (-2,-3) (Southeast)",
        location_name="Money Bag",
        global_object_id="city/ren223/yug2147",
        map_name="Moneybag 6",
        id=321,
    ),
    LocationData(
        region_name="SP (-1,-6) (South)",
        location_name="Money Bag (behind sign)",
        global_object_id="city/ren355/lor3013",
        map_name="Moneybag 8",
        id=341,
    ),
    LocationData(
        region_name="SP (-1,+4) (North)",
        location_name="Money Bag",
        global_object_id="city/lor2248/yug5046",
        map_name="Moneybag 9",
        id=351,
    ),
    LocationData(
        region_name="SP (+1,+4) (West)",
        location_name="Money Bags (winged) 1",
        global_object_id="city/yug4939/yug5160",
        map_name="Moneybag 10",
        id=361,
    ),
    LocationData(
        region_name="SP (+1,+4) (West)",
        location_name="Money Bags (winged) 2",
        global_object_id="city/yug4939/yug5162",
        map_name="Moneybag 10",
        id=362,
    ),
    LocationData(
        region_name="SP (+1,+4) (East)",
        location_name="Money Bag (left)",
        global_object_id="city/yug4939/yug5203",
        map_name="Moneybag 11",
        id=371,
    ),
    LocationData(
        region_name="SP (+1,+4) (East)",
        location_name="Money Bag (right)",
        global_object_id="city/yug4939/yug5166",
        map_name="Moneybag 12",
        id=381,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Left Musical Notes - Reward 1",
        global_object_id="city/ren223/yug5100",
        map_name="Musical Notes 1",
        id=401,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Left Musical Notes - Reward 2",
        global_object_id="city/ren223/yug5101",
        map_name="Musical Notes 1",
        id=402,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Left Musical Notes - Reward 3",
        global_object_id="city/ren223/yug5102",
        map_name="Musical Notes 1",
        id=403,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Left Musical Notes - Reward 4",
        global_object_id="city/ren223/yug5103",
        map_name="Musical Notes 1",
        id=404,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Right Musical Notes - Reward 1",
        global_object_id="city/ren223/yug5144",
        map_name="Musical Notes 2",
        id=421,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Right Musical Notes - Reward 2",
        global_object_id="city/ren223/yug5146",
        map_name="Musical Notes 2",
        id=422,
    ),
    LocationData(
        region_name="SP (-2,-3) (South)",
        location_name="Right Musical Notes - Reward 3",
        global_object_id="city/ren223/yug5147",
        map_name="Musical Notes 2",
        id=423,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Petal Container",
        global_object_id="city/ren223/yug5534",
        map_name="Petal Container 1",
        id=431,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Burger Quest - Reward 1",
        global_object_id="city/ren223/yug5539",
        map_name="Quest (Burger 1)",
        id=451,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Burger Quest - Reward 2",
        global_object_id="city/ren223/yug5540",
        map_name="Quest (Burger 1)",
        id=452,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Burger Quest - Reward 3",
        global_object_id="city/ren223/yug5541",
        map_name="Quest (Burger 1)",
        id=453,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Burger Quest - Reward 4",
        global_object_id="city/ren223/yug5545",
        map_name="Quest (Burger 1)",
        id=454,
    ),
    LocationData(
        region_name="SP (-2,-3) (Main)",
        location_name="Taxi Phone",
        global_object_id="city/ren223/lor2057",
        map_name="Taxi Phone 1",
        id=461,
    ),
]

EVENT_DATA: list[EventData] = [
    EventData(
        region_name="SP (-2,-3) (Main)",
        location_name="Combat (top-right, optional)",
        item_name="Complete",
        global_object_id="city/ren223/ren4804",
        map_name="Combat 1 (optional)",
    ),
    EventData(
        region_name="SP (-3,+3)",
        location_name="Combat",
        item_name="Complete",
        global_object_id="city/ren4152/lor2079",
        map_name="Combat 2",
    ),
    EventData(
        region_name="SP (-3,+4)",
        location_name="Combat",
        item_name="Complete",
        global_object_id="city/yug4930/yug4954",
        map_name="Combat 3",
    ),
    EventData(
        region_name="SP (-3,+4)",
        location_name="Key",
        item_name="Acquired",
        global_object_id="city/yug4930/yug4979",
        map_name="Key 1",
    ),
    EventData(
        region_name="SP (-2,-3) (Main)",
        location_name="Right Lever",
        item_name="Activated",
        global_object_id="city/ren223/yug5535",
        map_name="Lever 1",
    ),
    EventData(
        region_name="SP (-2,-3) (Main)",
        location_name="Left Lever",
        item_name="Activated",
        global_object_id="city/ren223/yug5536",
        map_name="Lever 2",
    ),
    EventData(
        region_name="SP (-2,-3) (Southeast)",
        location_name="Mole Brother 1",
        item_name="",
        global_object_id="city/ren223/lor1227",
        map_name="Mole Brother 1",
    ),
    EventData(
        region_name="SP (-2,-3) (South)",
        location_name="Left Musical Notes",
        item_name="",
        global_object_id="city/ren223/yug5074",
        map_name="Musical Notes 1",
    ),
    EventData(
        region_name="SP (-2,-3) (South)",
        location_name="Right Musical Notes",
        item_name="",
        global_object_id="city/ren223/yug5127",
        map_name="Musical Notes 2",
    ),
    EventData(
        region_name="SP (-2,-3) (Main)",
        location_name="Burger Quest",
        item_name="",
        global_object_id="city/ren223/yug3946",
        map_name="Quest (Burger 1)",
    ),
    EventData(
        region_name="SP Interiors (-1,+1)",
        location_name="Burger",
        item_name="Acquired",
        global_object_id="city_interiors/ren85/yug421",
        map_name="Burger",
    ),
    EventData(
        region_name="SP Sewers (-1,-5)",
        location_name="Left Lever",
        item_name="Activated",
        global_object_id="city_underground/ren984/lor227",
        map_name="Lever 2",
    ),
    EventData(
        region_name="SP Sewers (-1,-5)",
        location_name="Right Lever",
        item_name="Activated",
        global_object_id="city_underground/ren984/lor228",
        map_name="Lever 1",
    ),
]
