# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from .data_classes import ConnectionData, RoomData

ROOMS: list[RoomData] = [
    RoomData(room_label="Menu", room_area="Menu", region_name="Menu", global_room_id="", sort_key=""),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y-7) - yug3435",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y-7)",
        global_room_id="city/yug3435",
        sort_key="40893",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+1, Y-6) - lor1097",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+1,Y-6)",
        global_room_id="city/lor1097",
        sort_key="40094",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-6) - yug1263",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-6)",
        global_room_id="city/yug1263",
        sort_key="40294",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-6) - yug173",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-6)",
        global_room_id="city/yug173",
        sort_key="40394",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y-6) - yug171 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y-6) (Main)",
        global_room_id="city/yug171",
        sort_key="40694 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y-6) - yug171 (East)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y-6) (East)",
        global_room_id="city/yug171",
        sort_key="40694 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-6) - yug3298",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-6)",
        global_room_id="city/yug3298",
        sort_key="40794",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y-6) - yug3411",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y-6)",
        global_room_id="city/yug3411",
        sort_key="40894",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-5) - yug20",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-5)",
        global_room_id="city/yug20",
        sort_key="40295",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-5) - yug208 (North)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-5) (North)",
        global_room_id="city/yug208",
        sort_key="40395 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-5) - yug208 (South)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-5) (South)",
        global_room_id="city/yug208",
        sort_key="40395 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+5, Y-5) - yug183",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+5,Y-5)",
        global_room_id="city/yug183",
        sort_key="40495",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y-5) - yug23",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y-5)",
        global_room_id="city/yug23",
        sort_key="40595",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y-5) - yug3458",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y-5)",
        global_room_id="city/yug3458",
        sort_key="40695",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-5) - yug3276",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-5)",
        global_room_id="city/yug3276",
        sort_key="40795",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y-5) - yug3320 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y-5) (Main)",
        global_room_id="city/yug3320",
        sort_key="40895 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y-5) - yug3320 (South Alcove)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y-5) (South Alcove)",
        global_room_id="city/yug3320",
        sort_key="40895 (South Alcove)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y-4) - lor1128 (West)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y-4) (West)",
        global_room_id="city/lor1128",
        sort_key="40196 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y-4) - lor1128 (East)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y-4) (East)",
        global_room_id="city/lor1128",
        sort_key="40196 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-4) - yug19",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-4)",
        global_room_id="city/yug19",
        sort_key="40296",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+5, Y-4) - yug190",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+5,Y-4)",
        global_room_id="city/yug190",
        sort_key="40496",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y-4) - yug187",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y-4)",
        global_room_id="city/yug187",
        sort_key="40596",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y-4) - yug202 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y-4) (Main)",
        global_room_id="city/yug202",
        sort_key="40696 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y-4) - yug202 (West Alcove)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y-4) (West Alcove)",
        global_room_id="city/yug202",
        sort_key="40696 (West Alcove)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-4) - yug169",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-4)",
        global_room_id="city/yug169",
        sort_key="40796",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y-4) - yug3345",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y-4)",
        global_room_id="city/yug3345",
        sort_key="40896",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y-3) - lor1129",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y-3)",
        global_room_id="city/lor1129",
        sort_key="40197",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-3) - yug71",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-3)",
        global_room_id="city/yug71",
        sort_key="40297",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-3) - yug2741 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-3) (Main)",
        global_room_id="city/yug2741",
        sort_key="40397 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-3) - yug2741 (North)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-3) (North)",
        global_room_id="city/yug2741",
        sort_key="40397 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y-3) - yug2741 (East Alcove)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y-3) (East Alcove)",
        global_room_id="city/yug2741",
        sort_key="40397 (East Alcove)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Main)",
        global_room_id="city/yug108",
        sort_key="40797 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Northwest)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Northwest)",
        global_room_id="city/yug108",
        sort_key="40797 (Northwest)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Northeast)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Northeast)",
        global_room_id="city/yug108",
        sort_key="40797 (Northeast)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Southwest)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Southwest)",
        global_room_id="city/yug108",
        sort_key="40797 (Southwest)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Southeast)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Southeast)",
        global_room_id="city/yug108",
        sort_key="40797 (Southeast)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y-3) - yug108 (Dungeon Entrance)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y-3) (Dungeon Entrance)",
        global_room_id="city/yug108",
        sort_key="40797 (Dungeon Entrance)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y-3) - yug60",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y-3)",
        global_room_id="city/yug60",
        sort_key="40997",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y-2) - yug2715",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y-2)",
        global_room_id="city/yug2715",
        sort_key="40198",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-2) - yug259",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-2)",
        global_room_id="city/yug259",
        sort_key="40298",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y-2) - yug56 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y-2) (Main)",
        global_room_id="city/yug56",
        sort_key="40998 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y-2) - yug56 (East)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y-2) (East)",
        global_room_id="city/yug56",
        sort_key="40998 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y-1) - yug2440",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y-1)",
        global_room_id="city/yug2440",
        sort_key="40199",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y-1) - yug96",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y-1)",
        global_room_id="city/yug96",
        sort_key="40299",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y-1) - yug61 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y-1) (Main)",
        global_room_id="city/yug61",
        sort_key="40999 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y-1) - yug61 (West Alcove)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y-1) (West Alcove)",
        global_room_id="city/yug61",
        sort_key="40999 (West Alcove)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y+0) - yug220 (West)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y+0) (West)",
        global_room_id="city/yug220",
        sort_key="40200 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y+0) - yug220 (East)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y+0) (East)",
        global_room_id="city/yug220",
        sort_key="40200 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+0) - yug27 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+0) (Main)",
        global_room_id="city/yug27",
        sort_key="40400 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+0) - yug27 (North Alcove)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+0) (North Alcove)",
        global_room_id="city/yug27",
        sort_key="40400 (North Alcove)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+0) - yug55",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+0)",
        global_room_id="city/yug55",
        sort_key="41000",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y+1) - yug219 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y+1) (Main)",
        global_room_id="city/yug219",
        sort_key="40201 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y+1) - yug219 (House Entrance)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y+1) (House Entrance)",
        global_room_id="city/yug219",
        sort_key="40201 (House Entrance)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y+1) - yug17",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y+1)",
        global_room_id="city/yug17",
        sort_key="40801",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y+1) - yug18",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y+1)",
        global_room_id="city/yug18",
        sort_key="40901",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+1) - lor2298",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+1)",
        global_room_id="city/lor2298",
        sort_key="41001",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y+2) - yug15",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y+2)",
        global_room_id="city/yug15",
        sort_key="40802",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y+2) - yug22",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y+2)",
        global_room_id="city/yug22",
        sort_key="40902",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+2) - lor2334 (Main)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+2) (Main)",
        global_room_id="city/lor2334",
        sort_key="41002 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+2) - lor2334 (Northeast)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+2) (Northeast)",
        global_room_id="city/lor2334",
        sort_key="41002 (Northeast)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+11, Y+2) - lor2872",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+11,Y+2)",
        global_room_id="city/lor2872",
        sort_key="41102",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+2, Y+3) - yug1",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+2,Y+3)",
        global_room_id="city/yug1",
        sort_key="40203",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y+3) - yug217",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y+3)",
        global_room_id="city/yug217",
        sort_key="40303",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+3) - yug2 (West)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+3) (West)",
        global_room_id="city/yug2",
        sort_key="40403 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+3) - yug2 (East)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+3) (East)",
        global_room_id="city/yug2",
        sort_key="40403 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+5, Y+3) - yug2165",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+5,Y+3)",
        global_room_id="city/yug2165",
        sort_key="40503",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y+3) - yug2099 (North)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y+3) (North)",
        global_room_id="city/yug2099",
        sort_key="40603 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y+3) - yug2099 (South)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y+3) (South)",
        global_room_id="city/yug2099",
        sort_key="40603 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y+3) - yug9",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y+3)",
        global_room_id="city/yug9",
        sort_key="40703",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+3, Y+4) - yug4250",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+3,Y+4)",
        global_room_id="city/yug4250",
        sort_key="40304",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+4) - yug4303",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+4)",
        global_room_id="city/yug4303",
        sort_key="40404",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+5, Y+4) - yug4308",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+5,Y+4)",
        global_room_id="city/yug4308",
        sort_key="40504",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y+4) - yug4185",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y+4)",
        global_room_id="city/yug4185",
        sort_key="40604",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y+4) - yug4153 (North)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y+4) (North)",
        global_room_id="city/yug4153",
        sort_key="40704 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+7, Y+4) - yug4153 (South)",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+7,Y+4) (South)",
        global_room_id="city/yug4153",
        sort_key="40704 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+8, Y+4) - yug4144",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+8,Y+4)",
        global_room_id="city/yug4144",
        sort_key="40804",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y+4) - yug4136",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y+4)",
        global_room_id="city/yug4136",
        sort_key="40904",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+4) - yug4122",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+4)",
        global_room_id="city/yug4122",
        sort_key="41004",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+11, Y+4) - lor2884",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+11,Y+4)",
        global_room_id="city/lor2884",
        sort_key="41104",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+1, Y+5) - yug4288",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+1,Y+5)",
        global_room_id="city/yug4288",
        sort_key="40105",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+4, Y+5) - yug4222",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+4,Y+5)",
        global_room_id="city/yug4222",
        sort_key="40405",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+5, Y+5) - yug4236",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+5,Y+5)",
        global_room_id="city/yug4236",
        sort_key="40505",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+6, Y+5) - yug4194",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+6,Y+5)",
        global_room_id="city/yug4194",
        sort_key="40605",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+9, Y+5) - yug4113",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+9,Y+5)",
        global_room_id="city/yug4113",
        sort_key="40905",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+10, Y+5) - yug4798",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+10,Y+5)",
        global_room_id="city/yug4798",
        sort_key="41005",
    ),
    RoomData(
        room_label="Faria Slimer Borough (X+11, Y+5) - lor2866",
        room_area="Faria Slimer Borough",
        region_name="Faria (X+11,Y+5)",
        global_room_id="city/lor2866",
        sort_key="41105",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+6, Y-6) - yug134",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+6,Y-6)",
        global_room_id="city_interiors/yug134",
        sort_key="50594",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+8, Y-6) - yug426",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+8,Y-6)",
        global_room_id="city_interiors/yug426",
        sort_key="50794",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+4, Y-5) - yug47",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+4,Y-5)",
        global_room_id="city_interiors/yug47",
        sort_key="50395",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+3, Y-3) - yug1",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+3,Y-3)",
        global_room_id="city_interiors/yug1",
        sort_key="50297",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+7, Y-3) - lor414",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+7,Y-3)",
        global_room_id="city_interiors/lor414",
        sort_key="50697",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+10, Y-2) - yug59",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+10,Y-2)",
        global_room_id="city_interiors/yug59",
        sort_key="50998",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+2, Y-1) - yug69",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+2,Y-1)",
        global_room_id="city_interiors/yug69",
        sort_key="50199",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+5, Y+0) - lor296",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+5,Y+0)",
        global_room_id="city_interiors/lor296",
        sort_key="50500",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Interiors) (X+3, Y+1) - yug119",
        room_area="Faria Slimer Borough (Interiors)",
        region_name="Faria Interiors (X+3,Y+1)",
        global_room_id="city_interiors/yug119",
        sort_key="50301",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+3, Y-7) - ren3974",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+3,Y-7)",
        global_room_id="city_underground/ren3974",
        sort_key="60293",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-7) - ren3993 (Main)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-7) (Main)",
        global_room_id="city_underground/ren3993",
        sort_key="60393 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-7) - ren3993 (South)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-7) (South)",
        global_room_id="city_underground/ren3993",
        sort_key="60393 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-7) - yug882",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-7)",
        global_room_id="city_underground/yug882",
        sort_key="60793",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y-7) - yug873",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y-7)",
        global_room_id="city_underground/yug873",
        sort_key="60893",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+3, Y-6) - ren3946",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+3,Y-6)",
        global_room_id="city_underground/ren3946",
        sort_key="60294",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-6) - ren3982 (Main)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-6) (Main)",
        global_room_id="city_underground/ren3982",
        sort_key="60394 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-6) - ren3982 (North)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-6) (North)",
        global_room_id="city_underground/ren3982",
        sort_key="60394 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-6) - ren3982 (South)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-6) (South)",
        global_room_id="city_underground/ren3982",
        sort_key="60394 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y-6) - ren4029 (Main)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y-6) (Main)",
        global_room_id="city_underground/ren4029",
        sort_key="60494 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y-6) - ren4029 (South)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y-6) (South)",
        global_room_id="city_underground/ren4029",
        sort_key="60494 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y-6) - yug817",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y-6)",
        global_room_id="city_underground/yug817",
        sort_key="60694",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-6) - yug912 (Main)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-6) (Main)",
        global_room_id="city_underground/yug912",
        sort_key="60794 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-6) - yug912 (North)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-6) (North)",
        global_room_id="city_underground/yug912",
        sort_key="60794 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-6) - yug912 (Northwest)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-6) (Northwest)",
        global_room_id="city_underground/yug912",
        sort_key="60794 (Northwest)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-6) - yug912 (Northeast)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-6) (Northeast)",
        global_room_id="city_underground/yug912",
        sort_key="60794 (Northeast)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y-6) - yug860",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y-6)",
        global_room_id="city_underground/yug860",
        sort_key="60894",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+2, Y-5) - ren3998",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+2,Y-5)",
        global_room_id="city_underground/ren3998",
        sort_key="60195",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y-5) - ren3965",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y-5)",
        global_room_id="city_underground/ren3965",
        sort_key="60395",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y-5) - yug804",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y-5)",
        global_room_id="city_underground/yug804",
        sort_key="60695",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y-5) - yug838 (West)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y-5) (West)",
        global_room_id="city_underground/yug838",
        sort_key="60895 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y-5) - yug838 (East)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y-5) (East)",
        global_room_id="city_underground/yug838",
        sort_key="60895 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-4) - yug829",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-4)",
        global_room_id="city_underground/yug829",
        sort_key="60796",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y-4) - yug848",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y-4)",
        global_room_id="city_underground/yug848",
        sort_key="60896",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y-2) - lor177",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y-2)",
        global_room_id="city_underground/lor177",
        sort_key="60498",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y-2) - yug13",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y-2)",
        global_room_id="city_underground/yug13",
        sort_key="60598",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+2, Y-1) - ren1477",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+2,Y-1)",
        global_room_id="city_underground/ren1477",
        sort_key="60199",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y-1) - lor176",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y-1)",
        global_room_id="city_underground/lor176",
        sort_key="60499",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y-1) - yug31",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y-1)",
        global_room_id="city_underground/yug31",
        sort_key="60599",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y-1) - lor194",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y-1)",
        global_room_id="city_underground/lor194",
        sort_key="60699",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y-1) - yug23",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y-1)",
        global_room_id="city_underground/yug23",
        sort_key="60799",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+2, Y+0) - ren1453",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+2,Y+0)",
        global_room_id="city_underground/ren1453",
        sort_key="60200",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y+0) - lor175",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y+0)",
        global_room_id="city_underground/lor175",
        sort_key="60500",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+0) - yug26 (Main)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+0) (Main)",
        global_room_id="city_underground/yug26",
        sort_key="60600 (Main)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+0) - yug26 (North)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+0) (North)",
        global_room_id="city_underground/yug26",
        sort_key="60600 (North)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+0) - yug26 (South)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+0) (South)",
        global_room_id="city_underground/yug26",
        sort_key="60600 (South)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+0) - yug26 (East)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+0) (East)",
        global_room_id="city_underground/yug26",
        sort_key="60600 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y+0) - yug39",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y+0)",
        global_room_id="city_underground/yug39",
        sort_key="60700",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y+0) - yug20",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y+0)",
        global_room_id="city_underground/yug20",
        sort_key="60800",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+9, Y+0) - yug1330",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+9,Y+0)",
        global_room_id="city_underground/yug1330",
        sort_key="60900",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+10, Y+0) - yug1803",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+10,Y+0)",
        global_room_id="city_underground/yug1803",
        sort_key="61000",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y+1) - yug4",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y+1)",
        global_room_id="city_underground/yug4",
        sort_key="60501",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+1) - yug35",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+1)",
        global_room_id="city_underground/yug35",
        sort_key="60601",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y+1) - yug619",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y+1)",
        global_room_id="city_underground/yug619",
        sort_key="60801",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y+3) - yug47",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y+3)",
        global_room_id="city_underground/yug47",
        sort_key="60403",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+5, Y+3) - lor779",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+5,Y+3)",
        global_room_id="city_underground/lor779",
        sort_key="60503",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+3) - yug382",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+3)",
        global_room_id="city_underground/yug382",
        sort_key="60603",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y+3) - lor173 (West)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y+3) (West)",
        global_room_id="city_underground/lor173",
        sort_key="60703 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y+3) - lor173 (East)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y+3) (East)",
        global_room_id="city_underground/lor173",
        sort_key="60703 (East)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y+3) - yug1141",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y+3)",
        global_room_id="city_underground/yug1141",
        sort_key="60803",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+4, Y+4) - yug385",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+4,Y+4)",
        global_room_id="city_underground/yug385",
        sort_key="60404",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+6, Y+4) - yug528",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+6,Y+4)",
        global_room_id="city_underground/yug528",
        sort_key="60604",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+7, Y+4) - yug1206",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+7,Y+4)",
        global_room_id="city_underground/yug1206",
        sort_key="60704",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y+4) - ren3800 (West)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y+4) (West)",
        global_room_id="city_underground/ren3800",
        sort_key="60804 (West)",
    ),
    RoomData(
        room_label="Faria Slimer Borough (Sewers) (X+8, Y+4) - ren3800 (East)",
        room_area="Faria Slimer Borough (Sewers)",
        region_name="Faria Sewers (X+8,Y+4) (East)",
        global_room_id="city_underground/ren3800",
        sort_key="60804 (East)",
    ),
    RoomData(
        room_label="Safe House (X-1, Y+0) - lor127",
        room_area="Safe House",
        region_name="Safe House (X-1,Y+0)",
        global_room_id="safehouse/lor127",
        sort_key="0100",
    ),
    RoomData(
        room_label="Safe House (X+0, Y+0) - mig38",
        room_area="Safe House",
        region_name="Safe House (X+0,Y+0)",
        global_room_id="safehouse/mig38",
        sort_key="0000",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+0, Y-5) - lor151",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+0,Y-5)",
        global_room_id="skyscraper/lor151",
        sort_key="69995",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+1, Y-5) - lor133",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+1,Y-5)",
        global_room_id="skyscraper/lor133",
        sort_key="70095",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+2, Y-5) - lor98",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+2,Y-5)",
        global_room_id="skyscraper/lor98",
        sort_key="70195",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-5) - lor112",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-5)",
        global_room_id="skyscraper/lor112",
        sort_key="70295",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+4, Y-5) - lor104",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+4,Y-5)",
        global_room_id="skyscraper/lor104",
        sort_key="70395",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+0, Y-4) - lor187",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+0,Y-4)",
        global_room_id="skyscraper/lor187",
        sort_key="69996",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+1, Y-4) - lor150",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+1,Y-4)",
        global_room_id="skyscraper/lor150",
        sort_key="70096",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+2, Y-4) - lor140",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+2,Y-4)",
        global_room_id="skyscraper/lor140",
        sort_key="70196",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-4) - lor97 (Main)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-4) (Main)",
        global_room_id="skyscraper/lor97",
        sort_key="70296 (Main)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-4) - lor97 (North)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-4) (North)",
        global_room_id="skyscraper/lor97",
        sort_key="70296 (North)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-4) - lor97 (Southeast)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-4) (Southeast)",
        global_room_id="skyscraper/lor97",
        sort_key="70296 (Southeast)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+1, Y-3) - lor220",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+1,Y-3)",
        global_room_id="skyscraper/lor220",
        sort_key="70097",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+0, Y-2) - lor2 (West)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+0,Y-2) (West)",
        global_room_id="skyscraper/lor2",
        sort_key="69998 (West)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+0, Y-2) - lor2 (East)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+0,Y-2) (East)",
        global_room_id="skyscraper/lor2",
        sort_key="69998 (East)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+2, Y-2) - lor63 (West)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+2,Y-2) (West)",
        global_room_id="skyscraper/lor63",
        sort_key="70198 (West)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+2, Y-2) - lor63 (East)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+2,Y-2) (East)",
        global_room_id="skyscraper/lor63",
        sort_key="70198 (East)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+2, Y-1) - ren22",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+2,Y-1)",
        global_room_id="skyscraper/ren22",
        sort_key="70199",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-1) - lor25 (North)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-1) (North)",
        global_room_id="skyscraper/lor25",
        sort_key="70299 (North)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+3, Y-1) - lor25 (Southwest)",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+3,Y-1) (Southwest)",
        global_room_id="skyscraper/lor25",
        sort_key="70299 (Southwest)",
    ),
    RoomData(
        room_label="SlimeCorp Skyscraper (X+4, Y-1) - lor54",
        room_area="SlimeCorp Skyscraper",
        region_name="Skyscraper (X+4,Y-1)",
        global_room_id="skyscraper/lor54",
        sort_key="70399",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (North)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y-6) (North)",
        global_room_id="city/ren355",
        sort_key="10094 (North)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (South)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y-6) (South)",
        global_room_id="city/ren355",
        sort_key="10094 (South)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (West)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y-6) (West)",
        global_room_id="city/ren355",
        sort_key="10094 (West)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (East)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y-6) (East)",
        global_room_id="city/ren355",
        sort_key="10094 (East)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-4) - ren4064",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y-4)",
        global_room_id="city/ren4064",
        sort_key="10196",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y-4) - ren4066",
        room_area="South Plaza",
        region_name="S Plaza (X+1,Y-4)",
        global_room_id="city/ren4066",
        sort_key="10096",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Main)",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y-3) (Main)",
        global_room_id="city/ren223",
        sort_key="10197 (Main)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (South)",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y-3) (South)",
        global_room_id="city/ren223",
        sort_key="10197 (South)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southwest)",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y-3) (Southwest)",
        global_room_id="city/ren223",
        sort_key="10197 (Southwest)",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southeast)",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y-3) (Southeast)",
        global_room_id="city/ren223",
        sort_key="10197 (Southeast)",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+3) - ren4152",
        room_area="South Plaza",
        region_name="S Plaza (X-3,Y+3)",
        global_room_id="city/ren4152",
        sort_key="10303",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+4) - yug4930",
        room_area="South Plaza",
        region_name="S Plaza (X-3,Y+4)",
        global_room_id="city/yug4930",
        sort_key="10304",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y+4) - yug5210",
        room_area="South Plaza",
        region_name="S Plaza (X-2,Y+4)",
        global_room_id="city/yug5210",
        sort_key="10204",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (North)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y+4) (North)",
        global_room_id="city/lor2248",
        sort_key="10104 (North)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (South)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y+4) (South)",
        global_room_id="city/lor2248",
        sort_key="10104 (South)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (Southeast)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y+4) (Southeast)",
        global_room_id="city/lor2248",
        sort_key="10104 (Southeast)",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (Southeast Entrance)",
        room_area="South Plaza",
        region_name="S Plaza (X-1,Y+4) (Southeast Entrance)",
        global_room_id="city/lor2248",
        sort_key="10104 (Southeast Entrance)",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (West)",
        room_area="South Plaza",
        region_name="S Plaza (X+1,Y+4) (West)",
        global_room_id="city/yug4939",
        sort_key="10104 (West)",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (East)",
        room_area="South Plaza",
        region_name="S Plaza (X+1,Y+4) (East)",
        global_room_id="city/yug4939",
        sort_key="10104 (East)",
    ),
    RoomData(
        room_label="South Plaza (X+2, Y+4) - yug5154",
        room_area="South Plaza",
        region_name="S Plaza (X+2,Y+4)",
        global_room_id="city/yug5154",
        sort_key="10204",
    ),
    RoomData(
        room_label="South Plaza (Interiors) (X-1, Y+1) - ren85",
        room_area="South Plaza (Interiors)",
        region_name="S Plaza Interiors (X-1,Y+1)",
        global_room_id="city_interiors/ren85",
        sort_key="20101",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-6) - lor230",
        room_area="South Plaza (Sewers)",
        region_name="S Plaza Sewers (X-1,Y-6)",
        global_room_id="city_underground/lor230",
        sort_key="30094",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-5) - ren984",
        room_area="South Plaza (Sewers)",
        region_name="S Plaza Sewers (X-1,Y-5)",
        global_room_id="city_underground/ren984",
        sort_key="30095",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+4) - lor871",
        room_area="South Plaza (Sewers)",
        region_name="S Plaza Sewers (X-1,Y+4)",
        global_room_id="city_underground/lor871",
        sort_key="30104",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (West)",
        room_area="South Plaza (Sewers)",
        region_name="S Plaza Sewers (X-1,Y+5) (West)",
        global_room_id="city_underground/yug1700",
        sort_key="30105 (West)",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (East)",
        room_area="South Plaza (Sewers)",
        region_name="S Plaza Sewers (X-1,Y+5) (East)",
        global_room_id="city_underground/yug1700",
        sort_key="30105 (East)",
    ),
]

CONNECTIONS: list[ConnectionData] = [
    ConnectionData(start_region_name="Menu", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-7)", end_region_name="Faria Sewers (X+9,Y-7)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+9,Y-7)", end_region_name="Faria (X+9,Y-7)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+1,Y-6)", end_region_name="Faria (X+3,Y-6)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+1,Y-6)", end_region_name="S Plaza (X-1,Y-6) (East)", rule_strs=["dog", "ride"]
    ),
    ConnectionData(start_region_name="Faria (X+3,Y-6)", end_region_name="Faria Sewers (X+3,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+3,Y-6)", end_region_name="Faria (X+3,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-6)", end_region_name="Faria (X+7,Y-6) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-6) (Main)", end_region_name="Faria (X+4,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-6)", end_region_name="Faria (X+4,Y-5) (North)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-5) (North)", end_region_name="Faria (X+4,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-6)", end_region_name="Faria (X+6,Y-5)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+7,Y-6) (Main)",
        end_region_name="Faria (X+7,Y-6) (East)",
        rule_strs=["flip+", "dash, Bomb 1", "ufo, Bomb 1", "ride, Bomb 1"],
    ),
    ConnectionData(start_region_name="Faria (X+7,Y-6) (Main)", end_region_name="Faria (X+7,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-5)", end_region_name="Faria (X+7,Y-6) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-6) (East)", end_region_name="Faria (X+7,Y-6) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+7,Y-6) (East)", end_region_name="Faria Interiors (X+6,Y-6)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+6,Y-6)", end_region_name="Faria (X+7,Y-6) (East)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+8,Y-6)", end_region_name="Faria Interiors (X+8,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Interiors (X+8,Y-6)", end_region_name="Faria (X+8,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-6)", end_region_name="Faria (X+9,Y-7)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-7)", end_region_name="Faria (X+9,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-5)", end_region_name="Faria (X+3,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-6)", end_region_name="Faria (X+3,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-5)", end_region_name="Faria (X+3,Y-4)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y-5) (North)", end_region_name="Faria (X+4,Y-5) (South)", rule_strs=["Lever 4"]
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y-5) (North)", end_region_name="Faria Interiors (X+4,Y-5)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+4,Y-5)", end_region_name="Faria (X+4,Y-5) (North)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+4,Y-5) (South)", end_region_name="Faria (X+3,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+5,Y-5)", end_region_name="Faria (X+5,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+6,Y-5)", end_region_name="Faria (X+5,Y-5)", rule_strs=["Key 1"]),
    ConnectionData(start_region_name="Faria (X+6,Y-5)", end_region_name="Faria (X+6,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-5)", end_region_name="Faria (X+8,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-5)", end_region_name="Faria (X+7,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-5)", end_region_name="Faria (X+7,Y-4) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-4) (Main)", end_region_name="Faria (X+7,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y-5)", end_region_name="Faria (X+7,Y-4) (West Alcove)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-5)", end_region_name="Faria (X+8,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-6)", end_region_name="Faria (X+8,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-5)", end_region_name="Faria (X+9,Y-5) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-5) (Main)", end_region_name="Faria (X+8,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-5)", end_region_name="Faria Sewers (X+8,Y-6) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+8,Y-6) (Main)", end_region_name="Faria (X+8,Y-5)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-5) (Main)", end_region_name="Faria (X+9,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-6)", end_region_name="Faria (X+9,Y-5) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y-5) (South Alcove)", end_region_name="Faria (X+9,Y-4)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+2,Y-4) (West)", end_region_name="Faria (X+2,Y-4) (East)", rule_strs=["ufo", "ride"]
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y-4) (East)", end_region_name="Faria (X+2,Y-4) (West)", rule_strs=["ufo", "ride"]
    ),
    ConnectionData(start_region_name="Faria (X+2,Y-4) (East)", end_region_name="Faria (X+1,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+1,Y-6)", end_region_name="Faria (X+2,Y-4) (East)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y-4) (East)", end_region_name="Faria (X+2,Y-3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y-3)", end_region_name="Faria (X+2,Y-4) (East)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-4)", end_region_name="Faria (X+3,Y-5)", rule_strs=["Combat 1"]),
    ConnectionData(
        start_region_name="Faria (X+3,Y-4)", end_region_name="Faria (X+4,Y-5) (South)", rule_strs=["Combat 1"]
    ),
    ConnectionData(start_region_name="Faria (X+3,Y-4)", end_region_name="Faria (X+3,Y-3)", rule_strs=["Combat 1"]),
    ConnectionData(start_region_name="Faria (X+5,Y-4)", end_region_name="Faria (X+5,Y-5)", rule_strs=["Combat 2"]),
    ConnectionData(
        start_region_name="Faria (X+5,Y-4)", end_region_name="Faria (X+4,Y-3) (North)", rule_strs=["Combat 2"]
    ),
    ConnectionData(
        start_region_name="Faria (X+7,Y-4) (Main)", end_region_name="Faria (X+8,Y-4)", rule_strs=["dash", "ufo", "ride"]
    ),
    ConnectionData(start_region_name="Faria (X+7,Y-4) (Main)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+8,Y-4)", end_region_name="Faria (X+8,Y-3) (Northwest)", rule_strs=["Combat 4"]
    ),
    ConnectionData(start_region_name="Faria (X+9,Y-4)", end_region_name="Faria (X+9,Y-5) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-3)", end_region_name="Faria (X+3,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-3)", end_region_name="Faria Interiors (X+3,Y-3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Interiors (X+3,Y-3)", end_region_name="Faria (X+3,Y-3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (Main)", end_region_name="Faria (X+4,Y-5) (South)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-5) (South)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y-3) (Main)",
        end_region_name="Faria (X+7,Y-4) (Main)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride", "hard"],
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y-3) (Main)",
        end_region_name="Faria (X+4,Y+0) (North Alcove)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y-3) (Main)", end_region_name="Faria Interiors (X+7,Y-3)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+7,Y-3)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (Main)", end_region_name="Faria Sewers (X+6,Y-2)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+6,Y-2)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (Main)", end_region_name="Faria Sewers (X+7,Y-1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+7,Y-1)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (North)", end_region_name="Faria (X+5,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (North)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y-3) (North)", end_region_name="Skyscraper (X+0,Y-2) (West)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (West)", end_region_name="Faria (X+4,Y-3) (North)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Main)", end_region_name="Faria (X+8,Y-3) (Dungeon Entrance)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Main)", end_region_name="Faria (X+4,Y-3) (East Alcove)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Main)", end_region_name="Faria (X+10,Y-1) (West Alcove)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Northwest)",
        end_region_name="Faria (X+8,Y-3) (Northeast)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Northeast)", end_region_name="Faria (X+8,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Dungeon Entrance)", end_region_name="Faria (X+8,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Southwest)",
        end_region_name="Faria (X+8,Y-3) (Main)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Main)",
        end_region_name="Faria (X+8,Y-3) (Southwest)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Southwest)", end_region_name="Faria Sewers (X+8,Y+0)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y+0)", end_region_name="Faria (X+8,Y-3) (Southwest)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Southeast)", end_region_name="Faria (X+8,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Southeast)",
        end_region_name="Faria (X+10,Y+0)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y+0)",
        end_region_name="Faria (X+8,Y-3) (Southeast)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y-3)",
        end_region_name="Faria (X+8,Y-3) (Northeast)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y-2)",
        end_region_name="Faria (X+2,Y-1)",
        rule_strs=[
            "dash, Lever 1, Lever 3",
            "ride, Lever 1, Lever 2",
            "ride, Lever 1, Lever 3",
            "midair ufo, Lever 1, Lever 3",
        ],
    ),
    ConnectionData(start_region_name="Faria (X+3,Y-2)", end_region_name="Faria (X+2,Y-2)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y-2) (Main)", end_region_name="Faria (X+10,Y-3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y-3)", end_region_name="Faria (X+10,Y-2) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+10,Y-2) (Main)",
        end_region_name="Faria (X+10,Y-2) (East)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y-2) (East)",
        end_region_name="Faria (X+10,Y-2) (Main)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y-2) (East)", end_region_name="Faria Interiors (X+10,Y-2)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+10,Y-2)", end_region_name="Faria (X+10,Y-2) (East)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+2,Y-1)", end_region_name="Faria Interiors (X+2,Y-1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Interiors (X+2,Y-1)", end_region_name="Faria (X+2,Y-1)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+3,Y-1)", end_region_name="Faria (X+3,Y-2)", rule_strs=["dash", "ufo", "ride"]
    ),
    ConnectionData(start_region_name="Faria (X+3,Y-1)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria (X+3,Y-1)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+10,Y-1) (Main)", end_region_name="Faria (X+10,Y-2) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y-2) (Main)", end_region_name="Faria (X+10,Y-1) (Main)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+2,Y+0) (West)", end_region_name="Faria Sewers (X+2,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+2,Y+0)", end_region_name="Faria (X+2,Y+0) (West)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y+0) (East)", end_region_name="Faria (X+3,Y-1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y-1)", end_region_name="Faria (X+2,Y+0) (East)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y+0) (East)", end_region_name="Faria (X+2,Y+0) (West)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y+0) (East)", end_region_name="Faria Sewers (X+2,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+2,Y+0)", end_region_name="Faria (X+2,Y+0) (East)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria (X+4,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-3) (Main)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria (X+8,Y-3) (Southwest)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+8,Y-3) (Southwest)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria (X+4,Y+3) (East)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y+3) (East)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria Interiors (X+5,Y+0)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+5,Y+0)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+4,Y+0) (Main)", end_region_name="Faria Sewers (X+5,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y+1)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y+0)", end_region_name="Faria (X+10,Y-1) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y-1) (Main)", end_region_name="Faria (X+10,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y+0)", end_region_name="Faria (X+10,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y+0)", end_region_name="Faria Sewers (X+10,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+10,Y+0)", end_region_name="Faria (X+10,Y+0)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+2,Y+1) (Main)",
        end_region_name="Faria (X+2,Y+1) (House Entrance)",
        rule_strs=["Apple 1, Apple 2, Apple 3"],
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y+1) (House Entrance)", end_region_name="Faria (X+2,Y+1) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y+1) (House Entrance)", end_region_name="Faria Interiors (X+3,Y+1)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Interiors (X+3,Y+1)", end_region_name="Faria (X+2,Y+1) (House Entrance)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria (X+8,Y+1)", end_region_name="Faria (X+8,Y+2)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y+1)", end_region_name="Faria Sewers (X+8,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+8,Y+1)", end_region_name="Faria (X+8,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y+1)", end_region_name="Faria (X+8,Y-3) (Southeast)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y-3) (Southeast)", end_region_name="Faria (X+9,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+10,Y+1)", end_region_name="Faria (X+10,Y+2) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+8,Y+2)",
        end_region_name="Faria (X+8,Y+1)",
        rule_strs=["[SP] Mole Brother 1, Mole Brother 2"],
    ),
    ConnectionData(start_region_name="Faria (X+9,Y+2)", end_region_name="Faria (X+9,Y+1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y+1)", end_region_name="Faria (X+9,Y+2)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+9,Y+2)", end_region_name="Faria (X+8,Y+2)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+8,Y+2)", end_region_name="Faria (X+9,Y+2)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+10,Y+2) (Main)",
        end_region_name="Faria (X+10,Y+2) (Northeast)",
        rule_strs=["dog, ss", "dash", "ufo, ss+", "ride, ss+"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y+2) (Main)",
        end_region_name="Faria (X+11,Y+2)",
        rule_strs=["dog", "dash", "midair ufo", "ufo, ss", "ride, ss"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y+2) (Main)",
        end_region_name="Faria (X+10,Y+4)",
        rule_strs=["dog", "hard, dash, ss+, ride", "midair ufo, ss+"],
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y+3)",
        end_region_name="S Plaza (X-2,Y-3) (Southeast)",
        rule_strs=["[FSB] Combat 7"],
    ),
    ConnectionData(start_region_name="Faria (X+2,Y+3)", end_region_name="Faria (X+3,Y+3)", rule_strs=["Combat 7"]),
    ConnectionData(
        start_region_name="Faria (X+3,Y+3)", end_region_name="Faria (X+2,Y+1) (Main)", rule_strs=["dash", "ufo", "ride"]
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y+1) (Main)", end_region_name="Faria (X+3,Y+3)", rule_strs=["dash", "ufo", "ride"]
    ),
    ConnectionData(start_region_name="Faria (X+3,Y+3)", end_region_name="Faria (X+2,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y+3) (West)", end_region_name="Faria (X+3,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y+3)", end_region_name="Faria (X+4,Y+3) (West)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y+3) (West)", end_region_name="Faria Sewers (X+4,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+4,Y+3)", end_region_name="Faria (X+4,Y+3) (West)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+4,Y+3) (East)", end_region_name="Faria (X+4,Y+3) (West)", rule_strs=["Staff ID"]
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y+3) (West)", end_region_name="Faria (X+4,Y+3) (East)", rule_strs=["Staff ID"]
    ),
    ConnectionData(
        start_region_name="Faria (X+5,Y+3)", end_region_name="Faria (X+6,Y+3) (North)", rule_strs=["Combat 8"]
    ),
    ConnectionData(start_region_name="Faria (X+6,Y+3) (South)", end_region_name="Faria (X+5,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y+3)", end_region_name="Faria (X+4,Y+0) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y+3)", end_region_name="Faria (X+9,Y+2)", rule_strs=["Lever 5"]),
    ConnectionData(start_region_name="Faria (X+7,Y+3)", end_region_name="Faria (X+6,Y+3) (South)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+3,Y+4)", end_region_name="Faria (X+1,Y+5)", rule_strs=["Combat 6"]),
    ConnectionData(
        start_region_name="Faria (X+4,Y+4)",
        end_region_name="Faria (X+3,Y+4)",
        rule_strs=["ss, buoy", "dog", "dash, ss+", "ride, ss+", "dash, ride"],
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y+4)", end_region_name="Faria (X+5,Y+4)", rule_strs=["ss, buoy", "ss+", "dog"]
    ),
    ConnectionData(start_region_name="Faria (X+6,Y+4)", end_region_name="Faria (X+6,Y+5)", rule_strs=["ss", "buoy"]),
    ConnectionData(
        start_region_name="Faria (X+7,Y+4) (North)",
        end_region_name="Faria (X+7,Y+4) (South)",
        rule_strs=["ss", "dog", "dash", "ufo"],
    ),
    ConnectionData(start_region_name="Faria (X+7,Y+4) (North)", end_region_name="Faria (X+6,Y+4)", rule_strs=["Key 2"]),
    ConnectionData(
        start_region_name="Faria (X+8,Y+4)",
        end_region_name="Faria (X+7,Y+4) (North)",
        rule_strs=["dog", "dash, ss, ride", "ride, ss+", "hard, ride, dash"],
    ),
    ConnectionData(start_region_name="Faria (X+9,Y+4)", end_region_name="Faria (X+8,Y+4)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria (X+10,Y+4)", end_region_name="Faria (X+11,Y+4)", rule_strs=["dog", "ride, ss"]
    ),
    ConnectionData(
        start_region_name="Faria (X+11,Y+4)",
        end_region_name="Faria (X+10,Y+2) (Northeast)",
        rule_strs=["dog", "ride, ss"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y+2) (Northeast)",
        end_region_name="Faria (X+11,Y+4)",
        rule_strs=["dog", "ride, ss"],
    ),
    ConnectionData(
        start_region_name="Faria (X+11,Y+4)", end_region_name="Faria (X+11,Y+5)", rule_strs=["ss", "dog", "ufo", "ride"]
    ),
    ConnectionData(
        start_region_name="Faria (X+1,Y+5)",
        end_region_name="S Plaza (X-1,Y+4) (Southeast Entrance)",
        rule_strs=["dog, ride", "dash, ride", "ride, ss+", "buoy"],
    ),
    ConnectionData(
        start_region_name="Faria (X+4,Y+5)",
        end_region_name="Faria (X+4,Y+4)",
        rule_strs=["dog, buoy", "dog, ride", "dash, ride", "ride, ss+"],
    ),
    ConnectionData(
        start_region_name="Faria (X+5,Y+5)",
        end_region_name="Faria (X+4,Y+5)",
        rule_strs=["ss+, buoy", "dog, buoy", "dash, ss, buoy", "ride, buoy"],
    ),
    ConnectionData(
        start_region_name="Faria (X+6,Y+5)",
        end_region_name="Faria (X+5,Y+5)",
        rule_strs=["dog, buoy", "dog, ss", "dash, buoy", "dash, ss", "ufo, ride", "ride, buoy", "ride, ss"],
    ),
    ConnectionData(
        start_region_name="Faria (X+9,Y+5)",
        end_region_name="Faria (X+9,Y+4)",
        rule_strs=["dog", "dash, ride", "ride, ss+"],
    ),
    ConnectionData(
        start_region_name="Faria (X+10,Y+5)",
        end_region_name="Faria (X+9,Y+5)",
        rule_strs=["dog", "ride, ss+", "hard, ride, ss", "hard, ride, dash"],
    ),
    ConnectionData(
        start_region_name="Faria (X+11,Y+5)",
        end_region_name="Faria (X+10,Y+5)",
        rule_strs=["dog", "hard, ride, ss+", "hard, dash, ride, ss", "expert, dash, ride"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+3,Y-7)",
        end_region_name="Faria Sewers (X+4,Y-7) (Main)",
        rule_strs=["Lever 7, Lever 8"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-7) (Main)",
        end_region_name="Faria Sewers (X+4,Y-6) (North)",
        rule_strs=[],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-7) (South)", end_region_name="Faria Sewers (X+3,Y-7)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y-7)", end_region_name="Faria Sewers (X+8,Y-6) (North)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria Sewers (X+9,Y-7)", end_region_name="Faria Sewers (X+8,Y-7)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+3,Y-6)", end_region_name="Faria Sewers (X+4,Y-6) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-6) (Main)",
        end_region_name="Faria Sewers (X+4,Y-7) (South)",
        rule_strs=[],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-6) (Main)",
        end_region_name="Faria Sewers (X+5,Y-6) (Main)",
        rule_strs=["Key 1, Key 2, Button 1, Button 2"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-6) (Main)", end_region_name="Faria Sewers (X+2,Y-5)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+5,Y-6) (Main)",
        end_region_name="Faria Sewers (X+5,Y-6) (South)",
        rule_strs=["Key 3"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y-6) (South)", end_region_name="Faria (X+4,Y-6)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+4,Y-6)", end_region_name="Faria Sewers (X+5,Y-6) (South)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+7,Y-6)", end_region_name="Faria Sewers (X+8,Y-6) (Northwest)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y-6) (Main)", end_region_name="Faria Sewers (X+7,Y-5)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y-6) (Main)",
        end_region_name="Faria Sewers (X+9,Y-5) (West)",
        rule_strs=["Button 3, Button 4, Button 5"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y-6) (Main)", end_region_name="Faria Sewers (X+8,Y-4)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+9,Y-6)",
        end_region_name="Faria Sewers (X+8,Y-6) (Northeast)",
        rule_strs=["ufo", "off, [FSB-I] Key (shop)", "off, manhole"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+2,Y-5)", end_region_name="Faria Sewers (X+4,Y-5)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y-5)",
        end_region_name="Faria Sewers (X+4,Y-6) (South)",
        rule_strs=["Combat 4"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+7,Y-5)", end_region_name="Faria Sewers (X+7,Y-6)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+9,Y-5) (West)",
        end_region_name="Faria (X+9,Y-5) (South Alcove)",
        rule_strs=[],
    ),
    ConnectionData(
        start_region_name="Faria (X+9,Y-5) (South Alcove)",
        end_region_name="Faria Sewers (X+9,Y-5) (West)",
        rule_strs=[],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+9,Y-5) (East)",
        end_region_name="Faria Sewers (X+9,Y-6)",
        rule_strs=["[FSB-I] Key (shop)", "manhole"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y-4)",
        end_region_name="Faria Sewers (X+9,Y-4)",
        rule_strs=["manhole", "[FSB-I] Key (shop)"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+9,Y-4)",
        end_region_name="Faria Sewers (X+9,Y-5) (East)",
        rule_strs=["off, [FSB-I] Key (shop)", "off, manhole"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+6,Y-2)", end_region_name="Faria Sewers (X+6,Y-1)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y-1)", end_region_name="Faria Sewers (X+5,Y-2)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y-1)",
        end_region_name="Faria Sewers (X+6,Y+0) (North)",
        rule_strs=["Combat 8"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+7,Y-1)", end_region_name="Faria Sewers (X+8,Y-1)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+2,Y+0)",
        end_region_name="Faria Sewers (X+2,Y-1)",
        rule_strs=["ss+", "dog", "midair ufo", "ride, ss", "expert, ride"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+0) (North)", end_region_name="Faria Sewers (X+5,Y-1)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+0) (North)", end_region_name="Faria Sewers (X+5,Y+0)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+0) (South)", end_region_name="Faria Sewers (X+5,Y+0)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+0) (East)",
        end_region_name="Faria Sewers (X+6,Y+0) (Main)",
        rule_strs=["Lever 2, Lever 3, Lever 5"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+7,Y+0)",
        end_region_name="Faria Sewers (X+6,Y+0) (East)",
        rule_strs=["Combat 9"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+8,Y+0)", end_region_name="Faria Sewers (X+7,Y+0)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+10,Y+0)",
        end_region_name="Faria Sewers (X+9,Y+0)",
        rule_strs=["hard, dash", "ufo", "ride, dash"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y+1)", end_region_name="Faria Sewers (X+6,Y+1)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+1)",
        end_region_name="Faria Sewers (X+6,Y+0) (South)",
        rule_strs=["off", "ufo", "hard, ride"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+4,Y+3)", end_region_name="Faria Sewers (X+5,Y+3)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+5,Y+3)",
        end_region_name="Faria Sewers (X+4,Y+3)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y+3)", end_region_name="Faria Sewers (X+6,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+6,Y+3)", end_region_name="Faria Sewers (X+5,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria Sewers (X+5,Y+3)", end_region_name="Faria Sewers (X+4,Y+4)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+6,Y+3)", end_region_name="Faria Sewers (X+7,Y+3) (West)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+7,Y+3) (West)", end_region_name="Faria Sewers (X+6,Y+3)", rule_strs=[]
    ),
    ConnectionData(start_region_name="Faria Sewers (X+7,Y+3) (West)", end_region_name="Faria (X+7,Y+3)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+7,Y+3)", end_region_name="Faria Sewers (X+7,Y+3) (West)", rule_strs=[]),
    ConnectionData(
        start_region_name="Faria Sewers (X+7,Y+3) (West)",
        end_region_name="Faria Sewers (X+7,Y+3) (East)",
        rule_strs=["dash", "ride, midair ufo"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+7,Y+3) (East)", end_region_name="Faria Sewers (X+8,Y+3)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y+3)", end_region_name="Faria Sewers (X+8,Y+4) (East)", rule_strs=["dash"]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+4,Y+4)", end_region_name="Faria Sewers (X+6,Y+4)", rule_strs=["Combat 6"]
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y+4) (West)",
        end_region_name="Faria Sewers (X+7,Y+4)",
        rule_strs=["Combat 7"],
    ),
    ConnectionData(
        start_region_name="Faria Sewers (X+8,Y+4) (East)",
        end_region_name="Faria Sewers (X+8,Y+4) (West)",
        rule_strs=["dash", "ride"],
    ),
    ConnectionData(start_region_name="Safe House (X+0,Y+0)", end_region_name="Safe House (X-1,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="Safe House (X+0,Y+0)", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="Skyscraper (X+2,Y-5)", end_region_name="Skyscraper (X+1,Y-5)", rule_strs=["cog"]),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-5)", end_region_name="Skyscraper (X+2,Y-5)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-4)", end_region_name="Skyscraper (X+0,Y-5)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-4)", end_region_name="Skyscraper (X+1,Y-4)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+1,Y-4)", end_region_name="Skyscraper (X+0,Y-4)", rule_strs=["Combat 3"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+1,Y-4)",
        end_region_name="Skyscraper (X+1,Y-3)",
        rule_strs=["ufo", "ride, dash"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-4)",
        end_region_name="Skyscraper (X+3,Y-4) (Main)",
        rule_strs=["cog, off", "ride, dash"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-4)",
        end_region_name="Skyscraper (X+1,Y-3)",
        rule_strs=["cog, Key 3, Key 4", "hard, ride, dash"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (Main)",
        end_region_name="Skyscraper (X+2,Y-4)",
        rule_strs=["Key 3", "Key 4", "ride", "ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (Main)",
        end_region_name="Skyscraper (X+3,Y-4) (North)",
        rule_strs=["cog", "hard, dash, ride", "ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (Main)",
        end_region_name="Skyscraper (X+3,Y-4) (Southeast)",
        rule_strs=["cog, off", "ufo", "cog, dash, hard"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (North)", end_region_name="Skyscraper (X+3,Y-5)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (North)", end_region_name="Skyscraper (X+4,Y-5)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (Southeast)",
        end_region_name="Skyscraper (X+3,Y-4) (Main)",
        rule_strs=["none"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+1,Y-3)",
        end_region_name="Skyscraper (X+1,Y-4)",
        rule_strs=["cog, off", "ufo", "dash, ride, hard"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+1,Y-3)", end_region_name="Skyscraper (X+2,Y-4)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+1,Y-3)", end_region_name="Skyscraper (X+0,Y-2) (East)", rule_strs=["ufo"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (West)",
        end_region_name="Skyscraper (X+0,Y-4)",
        rule_strs=["ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (West)",
        end_region_name="Skyscraper (X+0,Y-2) (East)",
        rule_strs=["ufo", "cog"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (East)",
        end_region_name="Skyscraper (X+1,Y-3)",
        rule_strs=["ufo", "dash"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (East)",
        end_region_name="Skyscraper (X+2,Y-2) (West)",
        rule_strs=["Key 2", "ride", "ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+0,Y-2) (East)",
        end_region_name="Skyscraper (X+2,Y-1)",
        rule_strs=["ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-2) (West)",
        end_region_name="Skyscraper (X+0,Y-2) (East)",
        rule_strs=["Key 2", "ride", "dash", "ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-2) (West)",
        end_region_name="Skyscraper (X+2,Y-2) (East)",
        rule_strs=["Combat 2", "ride", "midair ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-2) (East)",
        end_region_name="Skyscraper (X+2,Y-2) (West)",
        rule_strs=["Combat 2", "ride", "midair ufo"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-2) (East)",
        end_region_name="Skyscraper (X+3,Y-4) (Main)",
        rule_strs=["none"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-4) (Main)",
        end_region_name="Skyscraper (X+2,Y-2) (East)",
        rule_strs=["none"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-1)", end_region_name="Skyscraper (X+0,Y-2) (East)", rule_strs=["none"]
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+2,Y-1)",
        end_region_name="Skyscraper (X+3,Y-1) (North)",
        rule_strs=["ufo", "dash"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-1) (North)",
        end_region_name="Skyscraper (X+3,Y-4) (Main)",
        rule_strs=["ufo", "dash, ride"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-1) (North)",
        end_region_name="Skyscraper (X+2,Y-1)",
        rule_strs=["Combat 1, cog", "Combat 1, ufo", "dash, ride", "ufo, ride"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-1) (North)",
        end_region_name="Skyscraper (X+4,Y-1)",
        rule_strs=["Combat 1, cog", "Combat 1, ufo", "dash, ride", "ufo, ride"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+3,Y-1) (Southwest)",
        end_region_name="Skyscraper (X+3,Y-1) (North)",
        rule_strs=["cog, off"],
    ),
    ConnectionData(
        start_region_name="Skyscraper (X+4,Y-1)",
        end_region_name="Skyscraper (X+3,Y-4) (Southeast)",
        rule_strs=["dash, ride, expert"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y-6) (North)", end_region_name="S Plaza (X-1,Y-6) (South)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y-6) (North)", end_region_name="S Plaza Sewers (X-1,Y-6)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y-6)", end_region_name="S Plaza (X-1,Y-6) (North)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y-6) (South)", end_region_name="S Plaza Sewers (X-1,Y-5)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y-5)", end_region_name="S Plaza (X-1,Y-6) (South)", rule_strs=[]
    ),
    ConnectionData(start_region_name="S Plaza (X-2,Y-4)", end_region_name="S Plaza (X-1,Y-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-1,Y-6) (South)", end_region_name="S Plaza (X-2,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X+1,Y-4)", end_region_name="Faria (X+2,Y-4) (West)", rule_strs=[]),
    ConnectionData(start_region_name="Faria (X+2,Y-4) (West)", end_region_name="S Plaza (X+1,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X+1,Y-4)", end_region_name="S Plaza (X-1,Y-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-1,Y-6) (South)", end_region_name="S Plaza (X+1,Y-4)", rule_strs=[]),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Main)", end_region_name="Faria (X+2,Y+0) (West)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="Faria (X+2,Y+0) (West)", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(start_region_name="S Plaza (X-2,Y-3) (Main)", end_region_name="Safe House (X+0,Y+0)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-2,Y-3) (Main)", end_region_name="S Plaza (X-2,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-2,Y-4)", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-2,Y-3) (Main)", end_region_name="S Plaza (X+1,Y-4)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X+1,Y-4)", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Main)",
        end_region_name="S Plaza (X-2,Y-3) (South)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (South)",
        end_region_name="S Plaza (X-2,Y-3) (Main)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Main)",
        end_region_name="S Plaza (X-2,Y-3) (Southwest)",
        rule_strs=["ss", "dog", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Southwest)",
        end_region_name="S Plaza (X-2,Y-3) (Main)",
        rule_strs=["ss", "dog", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Main)",
        end_region_name="S Plaza (X-2,Y-3) (Southeast)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Southeast)",
        end_region_name="S Plaza (X-2,Y-3) (Main)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Main)", end_region_name="S Plaza Interiors (X-1,Y+1)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza Interiors (X-1,Y+1)", end_region_name="S Plaza (X-2,Y-3) (Main)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (South)", end_region_name="S Plaza (X-1,Y+4) (North)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (North)", end_region_name="S Plaza (X-2,Y-3) (South)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-2,Y-3) (Southwest)", end_region_name="S Plaza (X-3,Y+3)", rule_strs=[]
    ),
    ConnectionData(start_region_name="S Plaza (X-2,Y-3) (Southeast)", end_region_name="Faria (X+2,Y+3)", rule_strs=[]),
    ConnectionData(
        start_region_name="S Plaza (X-3,Y+3)",
        end_region_name="S Plaza (X-2,Y-3) (Southwest)",
        rule_strs=["[SP] Combat 2"],
    ),
    ConnectionData(start_region_name="S Plaza (X-2,Y+4)", end_region_name="S Plaza (X-3,Y+4)", rule_strs=[]),
    ConnectionData(start_region_name="S Plaza (X-1,Y+4) (North)", end_region_name="S Plaza (X-2,Y+4)", rule_strs=[]),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (North)", end_region_name="S Plaza (X+1,Y+4) (West)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (South)", end_region_name="S Plaza (X-1,Y+4) (North)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (South)", end_region_name="S Plaza Sewers (X-1,Y+4)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y+4)", end_region_name="S Plaza (X-1,Y+4) (South)", rule_strs=[]
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (Southeast)",
        end_region_name="S Plaza (X-1,Y+4) (South)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X-1,Y+4) (Southeast Entrance)",
        end_region_name="S Plaza (X-1,Y+4) (Southeast)",
        rule_strs=["ss, Lever 3", "dog, Lever 3", "ufo, Lever 3", "ride", "buoy, Lever 3"],
    ),
    ConnectionData(
        start_region_name="S Plaza (X+1,Y+4) (West)",
        end_region_name="S Plaza (X+1,Y+4) (East)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(start_region_name="S Plaza (X+1,Y+4) (East)", end_region_name="S Plaza (X+2,Y+4)", rule_strs=[]),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y-5)",
        end_region_name="S Plaza Sewers (X-1,Y-6)",
        rule_strs=["Lever 1, Lever 2"],
    ),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y+4)",
        end_region_name="S Plaza Sewers (X-1,Y+5) (West)",
        rule_strs=["dog", "midair ufo, ss", "ride"],
    ),
    ConnectionData(
        start_region_name="S Plaza Sewers (X-1,Y+5) (West)",
        end_region_name="S Plaza Sewers (X-1,Y+5) (East)",
        rule_strs=["off, dog", "off, ride", "dog, ss"],
    ),
]
