# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from .data_classes import ConnectionData, RoomData

ROOMS: list[RoomData] = [
    RoomData(room_label="Menu", room_area="Menu", region_name="Menu", global_room_id=""),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (North)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (North)",
        global_room_id="city/ren355",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (South)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (South)",
        global_room_id="city/ren355",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (West)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (West)",
        global_room_id="city/ren355",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y-6) - ren355 (East)",
        room_area="South Plaza",
        region_name="SP (-1,-6) (East)",
        global_room_id="city/ren355",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-4) - ren4064",
        room_area="South Plaza",
        region_name="SP (-2,-4)",
        global_room_id="city/ren4064",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y-4) - ren4066",
        room_area="South Plaza",
        region_name="SP (+1,-4)",
        global_room_id="city/ren4066",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Main)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Main)",
        global_room_id="city/ren223",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (South)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (South)",
        global_room_id="city/ren223",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southwest)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Southwest)",
        global_room_id="city/ren223",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y-3) - ren223 (Southeast)",
        room_area="South Plaza",
        region_name="SP (-2,-3) (Southeast)",
        global_room_id="city/ren223",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+3) - ren4152",
        room_area="South Plaza",
        region_name="SP (-3,+3)",
        global_room_id="city/ren4152",
    ),
    RoomData(
        room_label="South Plaza (X-3, Y+4) - yug4930",
        room_area="South Plaza",
        region_name="SP (-3,+4)",
        global_room_id="city/yug4930",
    ),
    RoomData(
        room_label="South Plaza (X-2, Y+4) - yug5210",
        room_area="South Plaza",
        region_name="SP (-2,+4)",
        global_room_id="city/yug5210",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (North)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (North)",
        global_room_id="city/lor2248",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (South)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (South)",
        global_room_id="city/lor2248",
    ),
    RoomData(
        room_label="South Plaza (X-1, Y+4) - lor2248 (Southeast)",
        room_area="South Plaza",
        region_name="SP (-1,+4) (Southeast)",
        global_room_id="city/lor2248",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (West)",
        room_area="South Plaza",
        region_name="SP (+1,+4) (West)",
        global_room_id="city/yug4939",
    ),
    RoomData(
        room_label="South Plaza (X+1, Y+4) - yug4939 (East)",
        room_area="South Plaza",
        region_name="SP (+1,+4) (East)",
        global_room_id="city/yug4939",
    ),
    RoomData(
        room_label="South Plaza (X+2, Y+4) - yug5154",
        room_area="South Plaza",
        region_name="SP (+2,+4)",
        global_room_id="city/yug5154",
    ),
    RoomData(
        room_label="South Plaza (Interiors) (X-1, Y+1) - ren85",
        room_area="South Plaza (Interiors)",
        region_name="SP Interiors (-1,+1)",
        global_room_id="city_interiors/ren85",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-6) - lor230",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,-6)",
        global_room_id="city_underground/lor230",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y-5) - ren984",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,-5)",
        global_room_id="city_underground/ren984",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+4) - lor871",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+4)",
        global_room_id="city_underground/lor871",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (West)",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+5) (West)",
        global_room_id="city_underground/yug1700",
    ),
    RoomData(
        room_label="South Plaza (Sewers) (X-1, Y+5) - yug1700 (East)",
        room_area="South Plaza (Sewers)",
        region_name="SP Sewers (-1,+5) (East)",
        global_room_id="city_underground/yug1700",
    ),
]

CONNECTIONS: list[ConnectionData] = [
    ConnectionData(start_region_name="Menu", end_region_name="SP (-2,-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,-6) (North)", end_region_name="SP (-1,-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,-6) (North)", end_region_name="SP Sewers (-1,-6)", rule_strs=[]),
    ConnectionData(start_region_name="SP Sewers (-1,-6)", end_region_name="SP (-1,-6) (North)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP Sewers (-1,-5)", rule_strs=[]),
    ConnectionData(start_region_name="SP Sewers (-1,-5)", end_region_name="SP (-1,-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-4)", end_region_name="SP (-1,-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP (-2,-4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (+1,-4)", end_region_name="SP (-1,-6) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,-6) (South)", end_region_name="SP (+1,-4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (-2,-4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-4)", end_region_name="SP (-2,-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP (+1,-4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (+1,-4)", end_region_name="SP (-2,-3) (Main)", rule_strs=[]),
    ConnectionData(
        start_region_name="SP (-2,-3) (Main)",
        end_region_name="SP (-2,-3) (South)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="SP (-2,-3) (South)",
        end_region_name="SP (-2,-3) (Main)",
        rule_strs=["ss", "dog", "dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="SP (-2,-3) (Main)",
        end_region_name="SP (-2,-3) (Southwest)",
        rule_strs=["ss", "dog", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="SP (-2,-3) (Southwest)",
        end_region_name="SP (-2,-3) (Main)",
        rule_strs=["ss", "dog", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="SP (-2,-3) (Main)",
        end_region_name="SP (-2,-3) (Southeast)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(
        start_region_name="SP (-2,-3) (Southeast)",
        end_region_name="SP (-2,-3) (Main)",
        rule_strs=["dash", "ufo", "ride"],
    ),
    ConnectionData(start_region_name="SP (-2,-3) (Main)", end_region_name="SP Interiors (-1,+1)", rule_strs=[]),
    ConnectionData(start_region_name="SP Interiors (-1,+1)", end_region_name="SP (-2,-3) (Main)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-3) (South)", end_region_name="SP (-1,+4) (North)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (-2,-3) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-2,-3) (Southwest)", end_region_name="SP (-3,+3)", rule_strs=[]),
    ConnectionData(
        start_region_name="SP (-3,+3)", end_region_name="SP (-2,-3) (Southwest)", rule_strs=["[SP] Combat 2"]
    ),
    ConnectionData(start_region_name="SP (-2,+4)", end_region_name="SP (-3,+4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (-2,+4)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (North)", end_region_name="SP (+1,+4) (West)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (South)", end_region_name="SP (-1,+4) (North)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (South)", end_region_name="SP Sewers (-1,+4)", rule_strs=[]),
    ConnectionData(start_region_name="SP Sewers (-1,+4)", end_region_name="SP (-1,+4) (South)", rule_strs=[]),
    ConnectionData(start_region_name="SP (-1,+4) (Southeast)", end_region_name="SP (-1,+4) (South)", rule_strs=[]),
    ConnectionData(
        start_region_name="SP (+1,+4) (West)", end_region_name="SP (+1,+4) (East)", rule_strs=["dash", "ufo", "ride"]
    ),
    ConnectionData(start_region_name="SP (+1,+4) (East)", end_region_name="SP (+2,+4)", rule_strs=[]),
    ConnectionData(
        start_region_name="SP Sewers (-1,-5)", end_region_name="SP Sewers (-1,-6)", rule_strs=["Lever 1, Lever 2"]
    ),
    ConnectionData(
        start_region_name="SP Sewers (-1,+4)",
        end_region_name="SP Sewers (-1,+5) (West)",
        rule_strs=["dog", "midair ufo, ss", "ride"],
    ),
    ConnectionData(
        start_region_name="SP Sewers (-1,+5) (West)",
        end_region_name="SP Sewers (-1,+5) (East)",
        rule_strs=["ot, dog", "ot, ride", "dog, ss"],
    ),
]
