# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from typing import TYPE_CHECKING

from . import items
from .data.generated_locations import EVENT_DATA, LOCATION_DATA, LocationData, PipLocation

if TYPE_CHECKING:
    from .world import PipWorld


LOCATION_NAME_TO_ID = {d.full_location_name: d.id for d in LOCATION_DATA}
GLOBAL_OBJECT_ID_TO_LOCATION = {d.global_object_id: d for d in LOCATION_DATA}
GLOBAL_OBJECT_ID_TO_EVENT = {d.global_object_id: d for d in EVENT_DATA}


def create_all_locations(world: PipWorld) -> None:
    create_regular_locations(world)
    create_events(world)


def create_regular_locations(world: PipWorld) -> None:
    for d in LOCATION_DATA:
        loc_name_lower = d.location_name.lower()
        if "money bag" in loc_name_lower and not world.options.moneybags:
            continue

        if "combat" in loc_name_lower and "optional" in loc_name_lower and not world.options.optional_combats:
            continue

        r = world.get_region(d.region_name)
        r.add_locations({d.full_location_name: d.id}, PipLocation)


def create_events(world: PipWorld) -> None:
    pl = PipLocation
    pi = items.PipItem
    for d in EVENT_DATA:
        r = world.get_region(d.region_name)
        r.add_event(d.full_location_name, d.full_item_name, location_type=pl, item_type=pi)


def get_location(global_room_id: str) -> LocationData:
    return GLOBAL_OBJECT_ID_TO_LOCATION[global_room_id]


def get_event_item(global_room_id: str) -> str:
    return GLOBAL_OBJECT_ID_TO_EVENT[global_room_id].full_item_name
