# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
# RUN "Reformat Code" AFTER GENERATION.
from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Region

from .data.generated_regions import CONNECTIONS, ROOMS, RoomData

if TYPE_CHECKING:
    from .world import PipWorld


FULL_GLOBAL_ROOM_ID_TO_ROOM = {d.full_global_room_id: d for d in ROOMS}


def create_and_connect_regions(world: PipWorld) -> None:
    create_all_regions(world)
    connect_regions(world)


def create_all_regions(world: PipWorld) -> None:
    world.multiworld.regions += [Region(d.region_name, world.player, world.multiworld) for d in ROOMS]


def connect_regions(world: PipWorld) -> None:
    for d in CONNECTIONS:
        world.get_region(d.start_region_name).connect(world.get_region(d.end_region_name))


def get_room(full_global_room_id: str) -> RoomData:
    return FULL_GLOBAL_ROOM_ID_TO_ROOM[full_global_room_id]
